# Generated by Django 5.0.3 on 2024-03-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_alter_userasset_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assethistory',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='userasset',
            name='inferior_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='userasset',
            name='interval',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userasset',
            name='superior_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
    ]
