# Generated by Django 5.0.3 on 2024-03-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_alter_assethistory_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
