# Generated by Django 5.0.3 on 2024-03-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_asset_company_name_alter_asset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='currency',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
