# Generated by Django 5.0.3 on 2024-04-05 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_asset_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userasset',
            name='last_udpate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
