# Generated by Django 5.0.3 on 2024-04-18 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_userasset_last_udpate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userasset',
            name='is_buy_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userasset',
            name='is_sell_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assethistory',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='userasset',
            name='last_udpate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
